// MyDocumentContentRendererTests.swift -- Android-derived XHTML rendering contracts

import Foundation
import XCTest
@testable import BibleCore

final class MyDocumentContentRendererTests: XCTestCase {
    private struct AndroidMarkdownFixture: Decodable {
        let androidSource: String
        let markdown: String
        let xhtml: String

        enum CodingKeys: String, CodingKey {
            case androidSource = "android_source"
            case markdown
            case xhtml
        }
    }

    /**
     Verifies Markdown rendering byte-for-byte against Android's real CommonMark output.

     The fixture was generated by compiling Android's `MarkdownToXhtml.kt` against the exact
     dependency versions recorded in the fixture. It covers escaped text and link attributes,
     nested inline markup, tight and loose lists, GFM tables, hard breaks, code, and named HTML
     entities. The XML parse assertion prevents a fixture update from blessing malformed XHTML.
     */
    func testMarkdownRenderingMatchesAndroidXHTMLFixture() throws {
        let fixture = try loadFixture()
        XCTAssertEqual(
            fixture.androidSource,
            "app/src/main/java/net/bible/service/sword/mydocument/MarkdownToXhtml.kt"
        )

        let rendered = MyDocumentContentRenderer.render(fixture.markdown, contentType: .markdown)

        XCTAssertEqual(rendered, fixture.xhtml)
        assertWellFormedXML(rendered)
    }

    /**
     Verifies raw HTML uses Android's XML 1.1 escaping wrapper and OSIS remains unmodified.
     */
    func testHTMLIsEscapedAndOSISPassesThrough() throws {
        let html = "<p title=\"A&B\">'quoted'</p>"
        let renderedHTML = MyDocumentContentRenderer.render(html, contentType: .html)

        XCTAssertEqual(
            renderedHTML,
            "<div class=\"mydoc-html\"><html>&lt;p title=&quot;A&amp;B&quot;&gt;&apos;quoted&apos;&lt;/p&gt;</html></div>"
        )
        assertWellFormedXML(renderedHTML)
        XCTAssertEqual(MyDocumentContentRenderer.escapeXML11("\u{0001}\u{000B}"), "&#1;&#11;")

        let osis = "<div type=\"paragraph\"><w>Grace</w></div>"
        XCTAssertEqual(MyDocumentContentRenderer.render(osis, contentType: .osis), osis)
    }

    private func loadFixture() throws -> AndroidMarkdownFixture {
        let url = try XCTUnwrap(
            Bundle.module.url(
                forResource: "android-markdown-xhtml",
                withExtension: "json",
                subdirectory: "mydocuments"
            )
        )
        return try JSONDecoder().decode(AndroidMarkdownFixture.self, from: Data(contentsOf: url))
    }

    /**
     Validates rendered XHTML with the XML parser available on every supported Apple platform.

     - Parameters:
       - xml: Complete rendered fragment to parse.
       - file: XCTest source location forwarded to a failed assertion.
       - line: XCTest source line forwarded to a failed assertion.
     - Side effects: Performs an in-memory parse only.
     - Failure modes: Records an XCTest failure with the parser error when the fragment is not
       well-formed XML.
     */
    private func assertWellFormedXML(
        _ xml: String,
        file: StaticString = #filePath,
        line: UInt = #line
    ) {
        let parser = XMLParser(data: Data(xml.utf8))
        XCTAssertTrue(
            parser.parse(),
            parser.parserError?.localizedDescription ?? "XML parser rejected the rendered fragment",
            file: file,
            line: line
        )
    }
}
