import Foundation
import SwordKit
import XCTest
@testable import BibleCore

/**
 Contract tests for My Notes source-chapter mapping and canon traversal.

 Expected spans and headings come from Android `2e45efb0` with JSword `d1f4a4b9`, generated by
 `experiments/reader/MyNotesRangeOracle.java`, not from the Swift implementation under test. The
 versification resources, converter, and `VerseRange` naming source are byte-for-byte unchanged
 from iOS's pinned JSword ancestor `0da7412d`.

 These fixtures exercise expansion of an already selected source chapter, as retained by Android
 pseudo-document selection or synchronized target updates. They do not model explicit My Notes
 link admission, which maps the selected verse to KJVA before expanding that KJVA chapter.
 */
final class MyNotesChapterReferenceTests: XCTestCase {
    /**
     Verifies valid whole-source-chapter cases against the independent JSword oracle matrix.

     The matrix covers identity and explicit mappings, deuterocanonical content, verse-zero mapped
     starts, a mapped chapter boundary crossing, introduction-request normalization, and JSword's
     one-chapter whole-book heading.
     */
    func testMatchesPinnedAndroidWholeChapterRangeOracle() throws {
        typealias Fixture = (
            source: String,
            book: String,
            chapter: Int,
            ordinalStart: Int,
            ordinalEnd: Int,
            mappedStart: SwordVersification.Reference,
            mappedEnd: SwordVersification.Reference,
            heading: String
        )
        let fixtures: [Fixture] = [
            ("KJV", "Gen", 1, 4, 34, .init(osisBookId: "Gen", chapter: 1, verse: 1), .init(osisBookId: "Gen", chapter: 1, verse: 31), "Genesis 1"),
            ("KJV", "Gen", 0, 4, 4, .init(osisBookId: "Gen", chapter: 1, verse: 1), .init(osisBookId: "Gen", chapter: 1, verse: 1), "Genesis 1:1"),
            ("KJV", "Ps", 51, 15_242, 15_260, .init(osisBookId: "Ps", chapter: 51, verse: 1), .init(osisBookId: "Ps", chapter: 51, verse: 19), "Psalms 51"),
            ("KJVA", "Tob", 1, 25_466, 25_487, .init(osisBookId: "Tob", chapter: 1, verse: 1), .init(osisBookId: "Tob", chapter: 1, verse: 22), "Tobit 1"),
            ("Synodal", "Ps", 50, 15_241, 15_260, .init(osisBookId: "Ps", chapter: 51, verse: 0), .init(osisBookId: "Ps", chapter: 51, verse: 19), "Psalms 51"),
            ("Vulg", "Ps", 9, 14_529, 14_568, .init(osisBookId: "Ps", chapter: 9, verse: 0), .init(osisBookId: "Ps", chapter: 10, verse: 18), "Psalms 9-10"),
            ("Synodal", "Joel", 3, 23_254, 23_274, .init(osisBookId: "Joel", chapter: 3, verse: 1), .init(osisBookId: "Joel", chapter: 3, verse: 21), "Joel 3"),
            ("KJV", "Jude", 1, 37_821, 37_845, .init(osisBookId: "Jude", chapter: 1, verse: 1), .init(osisBookId: "Jude", chapter: 1, verse: 25), "Jude"),
        ]

        for fixture in fixtures {
            let result = try XCTUnwrap(
                MyNotesChapterReference(
                    sourceVersification: fixture.source,
                    sourceOSISBookId: fixture.book,
                    sourceChapter: fixture.chapter,
                    locale: Locale(identifier: "en_US")
                ),
                "\(fixture.source) \(fixture.book).\(fixture.chapter)"
            )
            XCTAssertEqual(result.source.versification, fixture.source)
            XCTAssertEqual(result.source.osisBookId, fixture.book)
            XCTAssertEqual(result.source.chapter, fixture.chapter)
            XCTAssertEqual(result.effectiveSourceChapter, max(fixture.chapter, 1))
            XCTAssertEqual(result.kjvaOrdinalStart, fixture.ordinalStart)
            XCTAssertEqual(result.kjvaOrdinalEnd, fixture.ordinalEnd)
            XCTAssertEqual(result.mappedKJVAStart, fixture.mappedStart)
            XCTAssertEqual(result.mappedKJVAEnd, fixture.mappedEnd)
            XCTAssertEqual(result.displayHeading, fixture.heading)
        }
    }

    /**
     Verifies public JSword fallback outputs do not become trusted My Notes ranges.

     The independent oracle records JSword's public fallback shapes for LXX Psalm 9 and Vulgate
     Daniel 14. Those coordinates are observably returned by Android's permissive converter but
     are not valid authoritative KJVA spans, so the production constructor must reject both.
     */
    func testRejectsPublicConverterFallbackRanges() {
        XCTAssertEqual(
            VersificationMapper.convert(
                osisBookId: "Ps",
                chapter: 9,
                verse: 40,
                from: "LXX",
                to: "KJVA"
            )?.fidelity,
            .fallback
        )
        XCTAssertNil(
            MyNotesChapterReference(
                sourceVersification: "LXX",
                sourceOSISBookId: "Ps",
                sourceChapter: 9,
                locale: Locale(identifier: "en_US")
            )
        )
        XCTAssertNil(
            MyNotesChapterReference(
                sourceVersification: "Vulg",
                sourceOSISBookId: "Dan",
                sourceChapter: 14,
                locale: Locale(identifier: "en_US")
            )
        )
        XCTAssertEqual(
            VersificationMapper.convert(
                osisBookId: "Dan",
                chapter: 14,
                verse: 1,
                from: "Vulg",
                to: "KJVA"
            )?.fidelity,
            .fallback
        )
    }

    /**
     Verifies a source chapter may map across KJVA books without being reduced or rejected.

     Android/JSword maps Catholic2 Esther 10 across canonical Esther and Additions to Esther. The
     expected endpoints, ordinals, and heading were captured by the same independent oracle using
     the actual public converter and `VerseRange.getName()`.
     */
    func testPreservesAuthoritativeMappedCrossBookSpan() throws {
        let result = try XCTUnwrap(
            MyNotesChapterReference(
                sourceVersification: "Catholic2",
                sourceOSISBookId: "Esth",
                sourceChapter: 10,
                locale: Locale(identifier: "en_US")
            )
        )
        XCTAssertEqual(result.kjvaOrdinalStart, 13_322)
        XCTAssertEqual(result.kjvaOrdinalEnd, 26_111)
        XCTAssertEqual(
            result.mappedKJVAStart,
            .init(osisBookId: "Esth", chapter: 10, verse: 1)
        )
        XCTAssertEqual(
            result.mappedKJVAEnd,
            .init(osisBookId: "AddEsth", chapter: 10, verse: 13)
        )
        XCTAssertEqual(result.displayHeading, "Esther 10-Additions to Esther 10")
    }

    /**
     Verifies invalid source identities fail without fabricating KJVA coordinates.
     */
    func testRejectsUnknownAndOutOfBoundsSourceChapters() {
        XCTAssertNil(
            MyNotesChapterReference(
                sourceVersification: "Unknown",
                sourceOSISBookId: "Gen",
                sourceChapter: 1
            )
        )
        XCTAssertNil(
            MyNotesChapterReference(
                sourceVersification: "KJV",
                sourceOSISBookId: "Gen",
                sourceChapter: -1
            )
        )
        XCTAssertNil(
            MyNotesChapterReference(
                sourceVersification: "KJV",
                sourceOSISBookId: "Gen",
                sourceChapter: 51
            )
        )
    }

    /**
     Verifies forward traversal advances chapters, skips unavailable books, and uses Android's
     asymmetric Genesis wrap when no eligible later book exists.
     */
    func testForwardTraversalMatchesAndroidBibleTraverser() throws {
        let intro = MyNotesSourceChapter(versification: "KJV", osisBookId: "Gen", chapter: 0)
        XCTAssertEqual(
            MyNotesChapterTraversal.next(after: intro, eligibleBookOSISIDs: ["Gen", "Exod"]),
            .init(versification: "KJV", osisBookId: "Gen", chapter: 1)
        )

        let genesisEnd = MyNotesSourceChapter(versification: "KJV", osisBookId: "Gen", chapter: 50)
        XCTAssertEqual(
            MyNotesChapterTraversal.next(
                after: genesisEnd,
                eligibleBookOSISIDs: ["Gen", "Lev"]
            ),
            .init(versification: "KJV", osisBookId: "Lev", chapter: 1)
        )

        let vulgateEstherFifteen = MyNotesSourceChapter(
            versification: "Vulg",
            osisBookId: "Esth",
            chapter: 15
        )
        XCTAssertEqual(
            MyNotesChapterTraversal.next(
                after: vulgateEstherFifteen,
                eligibleBookOSISIDs: ["Esth", "Dan"]
            ),
            .init(versification: "Vulg", osisBookId: "Esth", chapter: 16),
            "Traversal must use Vulgate's 16 Esther chapters rather than KJVA's 10"
        )

        let malachiEnd = MyNotesSourceChapter(
            versification: "KJVA",
            osisBookId: "Mal",
            chapter: 4
        )
        XCTAssertEqual(
            MyNotesChapterTraversal.next(
                after: malachiEnd,
                eligibleBookOSISIDs: ["Mal", "Tob", "Matt"]
            ),
            .init(versification: "KJVA", osisBookId: "Matt", chapter: 1),
            "Android skips eligible books whose KJV-scripture classification differs"
        )

        let revelationEnd = MyNotesSourceChapter(versification: "KJV", osisBookId: "Rev", chapter: 22)
        XCTAssertEqual(
            MyNotesChapterTraversal.next(
                after: revelationEnd,
                eligibleBookOSISIDs: ["Rev"]
            ),
            .init(versification: "KJV", osisBookId: "Gen", chapter: 1)
        )
    }

    /**
     Verifies backward traversal uses the previous eligible book and stays at the first chapter
     when no eligible predecessor exists instead of inventing a reverse wrap.
     */
    func testBackwardTraversalMatchesAndroidBibleTraverser() throws {
        let leviticusStart = MyNotesSourceChapter(
            versification: "KJV",
            osisBookId: "Lev",
            chapter: 1
        )
        XCTAssertEqual(
            MyNotesChapterTraversal.previous(
                before: leviticusStart,
                eligibleBookOSISIDs: ["Gen", "Lev"]
            ),
            .init(versification: "KJV", osisBookId: "Gen", chapter: 50)
        )

        let genesisStart = MyNotesSourceChapter(
            versification: "KJV",
            osisBookId: "Gen",
            chapter: 1
        )
        XCTAssertEqual(
            MyNotesChapterTraversal.previous(
                before: genesisStart,
                eligibleBookOSISIDs: ["Gen", "Rev"]
            ),
            genesisStart
        )
    }
}
