import Foundation
import XCTest
@testable import BibleCore
@testable import SwordKit

/**
 Decodes analyzer and query outputs generated by pinned JSword/Lucene dependencies.

 The fixture records authoritative Java outputs, not values inferred from the Swift port. Loading
 is deterministic and has no network or mutable process-state dependency.
 */
private struct SearchOracleFixture: Decodable {
    /** Immutable revisions and runtime used to generate the external Java outputs. */
    struct Provenance: Decodable {
        let androidRepositoryRevision: String
        let jswordRevision: String
        let luceneVersion: String
        let mmseg4jVersion: String
        let oracleRuntime: String
        let oracleImageDigest: String
    }

    /** One analyzer input and its complete ordered token stream. */
    struct AnalyzerCase: Decodable {
        let name: String
        let languageCode: String
        let input: String
        let tokens: [String]
    }

    /** One raw Android Search input and its Lucene/FTS compilation contract. */
    struct QueryCase: Decodable {
        let name: String
        let languageCode: String
        let wordMode: String
        let input: String
        let lucene: String?
        let luceneError: String?
        let fts: String?
        let error: String?
    }

    let provenance: Provenance
    let analyzers: [AnalyzerCase]
    let queries: [QueryCase]

    /** Loads the bundled, immutable Java oracle fixture. */
    static func load() throws -> SearchOracleFixture {
        guard let url = Bundle.module.url(
            forResource: "jsword-lucene-3.6.2-oracle",
            withExtension: "json",
            subdirectory: "search"
        ) else {
            throw SearchOracleFixtureError.missingResource
        }
        return try JSONDecoder().decode(Self.self, from: Data(contentsOf: url))
    }
}

/** Explicit fixture-loading failure used instead of silently skipping oracle assertions. */
private enum SearchOracleFixtureError: Error {
    case missingResource
}

/**
 Contract tests comparing iOS analyzer/query behavior with actual JSword/Lucene oracle output.

 The fixture was generated from JSword revision `0da7412d`, Lucene 3.6.2, and mmseg4j 1.8.6.
 Failures mean the runtime index/query pair has drifted from Android's analyzer or query semantics.
 */
final class SearchAnalyzerOracleTests: XCTestCase {
    /**
     Verifies every analyzer family and every configured Snowball language against Java tokens.

     This assertion also proves BibleCore's Lucene tables and mmseg dictionaries are present in the
     target bundle because those analyzers fail explicitly when resources are absent.
     */
    func testEveryAnalyzerFamilyMatchesPinnedJSwordOracle() throws {
        let fixture = try SearchOracleFixture.load()
        XCTAssertEqual(
            fixture.provenance.androidRepositoryRevision,
            "674cdfa279090f4ad1bff6c1a172adb4245c7a0d"
        )
        XCTAssertEqual(
            fixture.provenance.jswordRevision,
            SearchCanonicalBookCatalog.pinnedJSwordRevision
        )
        XCTAssertEqual(fixture.provenance.luceneVersion, "3.6.2")
        XCTAssertEqual(fixture.provenance.mmseg4jVersion, "1.8.6")
        XCTAssertEqual(fixture.provenance.oracleRuntime, "Eclipse Temurin 17.0.19+10, locale en_US")
        XCTAssertEqual(
            fixture.provenance.oracleImageDigest,
            "sha256:068a8f9ae4b74d9a20de3ecca771ba1a6437f1d7a8a8ad6deaf9dbdd2274397a"
        )
        XCTAssertEqual(fixture.analyzers.count, 23)
        XCTAssertTrue(fixture.analyzers.contains { $0.name == "greek_classic_scanner" })
        XCTAssertTrue(fixture.analyzers.contains { $0.name == "hebrew_classic_scanner" })

        let profiles = fixture.analyzers.map { SearchTextAnalyzer.profile(for: $0.languageCode) }
        XCTAssertEqual(
            Set(profiles.map { $0.kind.rawValue }),
            Set(SearchAnalyzerKind.allOracleFamilyNames)
        )
        XCTAssertEqual(
            Set(profiles.filter { $0.kind == .snowball }.map(\.languageCode)),
            Set(["da", "nl", "fi", "fr", "it", "no", "pt", "ru", "es", "sv"])
        )

        for oracle in fixture.analyzers {
            let profile = SearchTextAnalyzer.profile(for: oracle.languageCode)
            XCTAssertEqual(
                try SearchTextAnalyzer.analyzedTokens(oracle.input, profile: profile),
                oracle.tokens,
                "Analyzer oracle mismatch for \(oracle.name) [\(oracle.languageCode)]"
            )
        }
    }

    /**
     Verifies phrase, prefix, Boolean, punctuation, and unary semantics against Lucene output.

     Supported cases assert the exact FTS5 expression preserving the Lucene matching set. Features
     outside the implemented equivalent subset assert an explicit error and never reach SQLite.
     */
    func testQueryCompilerMatchesPinnedLuceneOracleAndExplicitSubset() throws {
        let fixture = try SearchOracleFixture.load()
        XCTAssertEqual(fixture.queries.count, 32)
        XCTAssertTrue(fixture.queries.contains { $0.name == "phrase" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "prefix" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "and" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "or" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "not" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "unary_required_prohibited" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "spaced_plus_bare_operator" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "spaced_minus_bare_operator" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "spaced_bang_bare_operator" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "or_attached_prohibited" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "symbolic_and" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "symbolic_or" })
        XCTAssertTrue(fixture.queries.contains { $0.name == "pure_bang_prohibited" })

        for oracle in fixture.queries {
            let mode = try wordMode(named: oracle.wordMode)
            let profile = SearchTextAnalyzer.profile(for: oracle.languageCode)
            if let expectedFTS = oracle.fts {
                XCTAssertEqual(
                    try SearchQueryCompiler.compile(
                        query: oracle.input,
                        wordMode: mode,
                        analyzer: profile
                    ),
                    expectedFTS,
                    "Query oracle mismatch for \(oracle.name); Lucene emitted \(oracle.lucene ?? "")"
                )
                XCTAssertEqual(
                    try SearchQueryCompiler.compile(
                        query: oracle.input,
                        wordMode: mode,
                        languageCode: oracle.languageCode
                    ),
                    expectedFTS,
                    "Public language-code compiler drift for \(oracle.name)"
                )
            } else {
                XCTAssertThrowsError(
                    try SearchQueryCompiler.compile(
                        query: oracle.input,
                        wordMode: mode,
                        analyzer: profile
                    ),
                    "Expected explicit \(oracle.error ?? "query") failure for \(oracle.name)"
                ) { error in
                    switch (oracle.error, error) {
                    case ("unsupportedQuerySyntax", SearchIndexError.unsupportedQuerySyntax):
                        break
                    case ("invalidQuery", SearchIndexError.invalidQuery):
                        break
                    default:
                        XCTFail(
                            "Wrong failure for \(oracle.name): \(error); " +
                                "Lucene oracle: \(oracle.luceneError ?? oracle.lucene ?? "unknown")"
                        )
                    }
                }
            }
        }
    }

    /** Converts stable fixture spellings into SwordKit's public Search mode values. */
    private func wordMode(named value: String) throws -> SearchWordMode {
        switch value {
        case "allWords": return .allWords
        case "anyWord": return .anyWord
        case "phrase": return .phrase
        default: throw SearchOracleFixtureError.missingResource
        }
    }
}

/** Stable analyzer-family names required in the external oracle matrix. */
private extension SearchAnalyzerKind {
    static let allOracleFamilyNames = [
        "simple", "arabic", "czech", "german", "greek", "persian", "hebrew", "cjk", "thai",
        "snowball",
    ]
}
