// BibleReaderDocumentReplacementEmitter.swift — Android-parity Vue document replacement

import BibleView

/**
 Owns the shared reader transaction used whenever one Vue document replaces another.

 Android's `BibleView.replaceDocument()` sends `clear_document`, the current initial config,
 `add_documents`, and `setup_content` in one JavaScript evaluation. This emitter keeps every iOS
 document surface on that same contract while allowing the controller to resolve configuration at
 the moment of replacement.

 Inputs:
 - the pane's active `BibleBridge`
 - a live builder for window/workspace/global-resolved configuration
 - a complete typed or pre-serialized document plus setup payload

 Outputs:
 - one atomic bridge evaluation in Android event order

 Side effects:
 - replaces the current Vue document when payload encoding and bridge dispatch succeed

 Failure modes:
 - returns `false` without clearing the current document when payload encoding fails
 - returns `false` when the bridge has neither an attached WebView nor a test observer
 */
struct BibleReaderDocumentReplacementEmitter {
    /// Active pane bridge used for the atomic JavaScript evaluation.
    private let bridge: BibleBridge
    /// Resolves the current config with Android's `initial: true` replacement semantics.
    private let buildInitialConfigJSON: () -> String

    /**
     Creates a replacement emitter bound to one reader pane.

     - Parameters:
       - bridge: Active reader bridge.
       - buildInitialConfigJSON: Closure resolving current pane configuration at dispatch time.
     - Side effects: None during initialization.
     - Failure modes: None.
     */
    init(
        bridge: BibleBridge,
        buildInitialConfigJSON: @escaping () -> String
    ) {
        self.bridge = bridge
        self.buildInitialConfigJSON = buildInitialConfigJSON
    }

    /**
     Atomically emits one typed document and its setup payload.

     - Parameters:
       - document: Complete Encodable Vue document payload.
       - setup: Setup/scroll payload for the replacement content.
     - Returns: `true` when encoding succeeds and the bridge queues the transaction.
     - Side effects: Resolves live pane configuration and replaces the visible Vue document.
     - Failure modes: Returns `false` without clearing existing content on encoding/dispatch failure.
     */
    @discardableResult
    func replace<Document: Encodable>(
        document: Document,
        setup: ReaderSetupContentPayload
    ) -> Bool {
        bridge.replaceDocument(
            configData: buildInitialConfigJSON(),
            document: document,
            setup: setup
        )
    }

    /**
     Atomically emits one pre-serialized document and typed setup payload.

     - Parameters:
       - documentJSON: Complete raw JSON document generated by a shared payload factory.
       - setup: Setup/scroll payload for the replacement content.
     - Returns: `true` when setup encoding succeeds and the bridge queues the transaction.
     - Side effects: Resolves live pane configuration and replaces the visible Vue document.
     - Failure modes: Returns `false` without clearing existing content on encoding/dispatch failure.
     */
    @discardableResult
    func replace(
        documentJSON: String,
        setup: ReaderSetupContentPayload
    ) -> Bool {
        bridge.replaceDocument(
            configData: buildInitialConfigJSON(),
            documentData: documentJSON,
            setup: setup
        )
    }
}
