import Foundation

/**
 Pinned Android 37 TagSoup element containment model used by Search preview projection.

 The namespace loads a generated, integrity-checked resource once and exposes immutable lookup and
 bogon-construction operations. It performs no external writes; missing/corrupt resources fail
 closed to empty lookup, which focused bundle-integrity tests treat as a build blocker.
 */
enum SwordTagSoupHTMLSchema {
    /// Number of element declarations generated by Android 37's `HTMLSchema` constructor.
    static let expectedBundledElementCount = 108

    /// TagSoup's restartable-inline element flag.
    static let restartFlag: UInt32 = 1
    /// TagSoup's scanner-CDATA element flag.
    static let cdataFlag: UInt32 = 2
    /// TagSoup's do-not-force-close element flag.
    static let noForceFlag: UInt32 = 4

    /**
     Stores one immutable element declaration from Android's generated HTML schema.

     The value carries only containment/flag metadata and performs no external mutation. Invalid
     resource rows are rejected before construction; runtime bogons use the same representation.
     */
    struct ElementType: Equatable {
        /// Canonical schema QName, or the repaired source QName for one runtime bogon.
        let name: String
        /// Bitmask of child-membership classes this element accepts.
        let model: UInt32
        /// Bitmask of parent content models this element can occupy.
        let memberOf: UInt32
        /// TagSoup restart, CDATA, and no-force flags.
        let flags: UInt32
        /// Canonical natural parent used when parser rectification must synthesize structure.
        let parentName: String?

        /// SAX local name derived from the first QName colon exactly as TagSoup does.
        var localName: String {
            guard let colon = name.firstIndex(of: ":") else { return name }
            return String(name[name.index(after: colon)...])
        }

        /**
         Tests whether this element's schema model accepts one candidate membership class.

         - Parameter candidate: Child type being rectified by the parser.
         - Returns: True when the model/member bitmasks intersect.
         - Side effects: None.
         - Failure modes: None.
         */
        func canContain(_ candidate: ElementType) -> Bool {
            model & candidate.memberOf != 0
        }
    }

    /// Validated schema declarations cached on first preview projection.
    private static let bundledElements: [String: ElementType] = {
        guard let url = Bundle.module.url(
                  forResource: "html-schema-android-37-elements",
                  withExtension: "tsv",
                  subdirectory: "tagsoup"
              ),
              let contents = try? String(contentsOf: url, encoding: .utf8) else {
            return [:]
        }
        var result: [String: ElementType] = [:]
        for line in contents.split(whereSeparator: \.isNewline) {
            guard !line.hasPrefix("#") else { continue }
            let fields = line.split(separator: "\t", omittingEmptySubsequences: false)
            guard (fields.count == 4 || fields.count == 5),
                  let model = UInt32(fields[1], radix: 16),
                  let memberOf = UInt32(fields[2], radix: 16),
                  let flags = UInt32(fields[3], radix: 16) else {
                return [:]
            }
            let name = String(fields[0])
            guard result[name] == nil else { return [:] }
            result[name] = ElementType(
                name: name,
                model: model,
                memberOf: memberOf,
                flags: flags,
                parentName: fields.count == 5 ? String(fields[4]) : nil
            )
        }
        guard result.count == expectedBundledElementCount,
              result["<root>"]?.model == 0x8000_0000,
              result["<pcdata>"]?.memberOf == 0x4000_0000,
              result["p"]?.model == 0x4010_1000,
              (result["script"]?.flags ?? 0) & cdataFlag != 0,
              (result["form"]?.flags ?? 0) & noForceFlag != 0 else {
            return [:]
        }
        return result
    }()

    /// Test-visible integrity signal for the generated Android schema resource.
    static var bundledElementCount: Int {
        bundledElements.count
    }

    /**
     Resolves one repaired QName using Android `Schema.getElementType` root-lowercasing semantics.

     - Parameter repairedName: TagSoup `Parser.makeName` output.
     - Returns: A pinned schema declaration, or nil when TagSoup must create a runtime bogon.
     - Side effects: Loads and validates the generated schema table on first use.
     - Failure modes: Returns nil for every name when the generated resource is unavailable.
     */
    static func knownElement(named repairedName: String) -> ElementType? {
        bundledElements[SwordJavaTextCompatibility.lowercasedRoot(repairedName)]
    }

    /**
     Creates TagSoup's default non-root runtime declaration for an unknown repaired QName.

     - Parameter repairedName: Nonempty name returned by `Parser.makeName`.
     - Returns: An unrestricted element rooted directly under TagSoup's synthetic root.
     - Side effects: None; the caller owns document-local identity caching.
     - Failure modes: None.
     */
    static func bogon(named repairedName: String) -> ElementType {
        ElementType(
            name: repairedName,
            model: 0xFFFF_FFFF,
            memberOf: 0xFFFF_FFFF,
            flags: 0,
            parentName: nil
        )
    }

    /**
     Returns one canonical declaration for parser-created natural parents.

     - Parameter name: Exact already-lowercased schema key such as `html` or `<pcdata>`.
     - Returns: Pinned declaration, or nil for absent/resource-invalid input.
     - Side effects: Loads and validates the schema resource on first use.
     - Failure modes: Returns nil rather than synthesizing a bogon; callers decide repair policy.
     */
    static func element(namedCanonicalName name: String) -> ElementType? {
        bundledElements[name]
    }
}
